export const SET_GAME_CONFIG_DATA = 'SET_GAME_CONFIG_DATA';
export const FORM_GAME_QUESTIONS = 'FORM_GAME_QUESTIONS';
export const TOGGLE_IS_LOADED = 'TOGGLE_IS_LOADED';

export const INCREASE_SCORE = 'INCREASE_SCORE';
export const SET_SCORE_QUESTION = 'SET_SCORE_QUESTION';

export const SET_ANSWER = 'SET_ANSWER';
export const SET_SELECTED_AND_DISABLED = 'SET_SELECTED_AND_DISABLED';

export const SHOW_CORRECT_ANSWER = 'SHOW_CORRECT_ANSWER';
export const SET_EARNED = 'SET_EARNED';

export const UPDATE_SCORE_DASHBOARD = 'UPDATE_SCORE_DASHBOARD';

export const RESET_SCORE = 'RESET_SCORE';
export const RESET_EARNED = 'RESET_EARNED';

export const DISABLE_IS_INIT_LOAD = 'DISABLE_IS_INIT_LOAD';
export const SET_IS_IN_GAME = 'SET_IS_IN_GAME';
export const SET_IS_IN_GAME_END = 'SET_IS_IN_GAME_END';

export const SET_LOAD_ERROR = 'SET_LOAD_ERROR';
